### ISSUE TITLE
Data_extractor on cvl dataset error

### ISSUE THREAD

**Issue by kevinkmldn** [Breta01/handwriting-ocr#105]
i tried to extract dataset cvl but got an error while the others datasets is working fine.

C:\Users\mrnol\handwriting-ocr\src\data>python data_extractor.py -d cvl
Processing - cvl
Traceback (most recent call last):
  File "data_extractor.py", line 47, in <module>
    entry[0](entry[1], output_folder, entry[2])
  File "C:\Users\mrnol\handwriting-ocr\src\data\datasets\cvl.py", line 24, in extract
    word = re.search('\/\d+-\d+-\d+-\d+-(.+?).tif', im).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by 17sushmita** [comment]
Replace 
word = re.search('\d+-\d+-\d+-\d+-(.+?).tif', im).group(1)
instead of
word = re.search('/\d+-\d+-\d+-\d+-(.+?).tif', im).group(1)
