### ISSUE TITLE
No digital training set found

### ISSUE THREAD

**Issue by juparrrr** [Breta01/handwriting-ocr#25]
Hello, can this project identify numbers in handwritten texts?

**Comment by Breta01** [comment]
It can't right now, because I don't have the dataset for it. But there is a lot of projects using MNIST dataset for identifying handwritten numbers.

**Comment by juparrrr** [comment]
Thank you for your reply. I'm doing a test paper writing recognition system. Before that, I used CNN neural network to train data, but the problem of text segmentation encountered difficulties. So this project needs text segmentation?

**Comment by Breta01** [comment]
It depends on recognition method. In one approach, I test segmentation of text by bidirectional RNN and then classifying individual characters using CNN. I also test classification using CTC which process images of whole words (could be transformed to process whole lines of words).

**Comment by juparrrr** [comment]
The project I am working on is a exam writing recognition system, so I would like to ask which of the classification methods is more appropriate. And want to know CTC, Bi-RNN and CNN's output is a character sequence or a word?

**Comment by Breta01** [comment]
Yes, for the CNN you need single-letter dataset. For Bi-RNN you need dataset containing images of whole words along with text files containing positions of lines separating individual letters. If you have the words already, you can use [WordClassDM.py](https://github.com/Breta01/handwriting-ocr/blob/master/WordClassDM.py) for manual creation of letter separating lines.

**Comment by juparrrr** [comment]
thank you for your reply. Is Gap = charSeg.segmentation (img, RNN = True, debug = True) in OCR.ipynb to do the word cut and then use the model trained by CharClassifier.ipynb to identify it? Does the gap use the model 'models/gap-clas/RNN/Bi-RNN-new' to perform the cutting task?
So what do you mean by "The current GapClassifier which detects the borders between letters was trained on my handwriting and it fails on a handwriting of others." Means that this model can't be used for word cutting that you can't write to others other than you?

**Comment by Breta01** [comment]
Ok, yes you need two models and in OCR.ipynb is used the Classifier-BiRNN.ipynb.

I train both models from data/words2/ because it contains images of words along with files which contains the positions of gaplines. For CharClassifier I just cut out those separated letters... If you have letter and word training sets, you can process word set with WordClassDM.py (need manual work) and than train the two models. (If you have individual letters, you can possibly create artificial words for training with already know positions of gaplines, but I don't have code for that.)

GapClassifier-BiRNN-Attention.ipynb, GapClassifier-Attention-RNN.ipynb, GapClassification-CharClass.ipynb, and GapClassifier.ipynb are only experimental models which don't perform so good. Just skip those files.

GapClassification.ipynb deomstrates the process of separation of characters, but final code for separation is in [ocr/charSeg.py](https://github.com/Breta01/handwriting-ocr/blob/master/ocr/charSeg.py).

**Comment by juparrrr** [comment]
The WordClassDM.py runtime has this problem,The data in the original words_raw :
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cv::cvtColor, file C:\ci\opencv_1512688052760\work\modules\imgproc\src\color.cpp, line 11016
Traceback (most recent call last):
  File "E:/jupar/handwriting-ocr-master/WordClassDM.py", line 222, in <module>
    Cycler(args.index, args.data, args.save)
  File "E:/jupar/handwriting-ocr-master/WordClassDM.py", line 80, in __init__
    self.blockLoad()
  File "E:/jupar/handwriting-ocr-master/WordClassDM.py", line 122, in blockLoad
    self.data_loc, self.org_idx + self.idx, 100)
  File "E:/jupar/handwriting-ocr-master/WordClassDM.py", line 49, in loadImages
    cv2.cvtColor(cv2.imread(img), cv2.COLOR_BGR2RGB),
cv2.error: C:\ci\opencv_1512688052760\work\modules\imgproc\src\color.cpp:11016: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor

**Comment by juparrrr** [comment]
When working with words_raw's image through WordClassDM.py, I encountered this problem:
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cv::cvtColor, file C:\ci\opencv_1512688052760\work\modules\imgproc\src\color.cpp, line 11016
Traceback (most recent call last):
  File "E:/jupar/handwriting-ocr-master/WordClassDM.py", line 222, in <module>
    Cycler(args.index, args.data, args.save)
  File "E:/jupar/handwriting-ocr-master/WordClassDM.py", line 80, in __init__
    self.blockLoad()
  File "E:/jupar/handwriting-ocr-master/WordClassDM.py", line 122, in blockLoad
    self.data_loc, self.org_idx + self.idx, 100)
  File "E:/jupar/handwriting-ocr-master/WordClassDM.py", line 49, in loadImages
    cv2.cvtColor(cv2.imread(img), cv2.COLOR_BGR2RGB),
cv2.error: C:\ci\opencv_1512688052760\work\modules\imgproc\src\color.cpp:11016: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor

**Comment by juparrrr** [comment]
This problem is encountered in running WordClassDM.py:
Traceback (most recent call last):
  File "E:/Jupar/handwriting-ocr-master/WordClassDM.py", line 218, in <module>
    Cycler(args.index, args.data, args.save)
  File "E:/Jupar/handwriting-ocr-master/WordClassDM.py", line 76, in __init__
    self.blockLoad()
  File "E:/Jupar/handwriting-ocr-master/WordClassDM.py", line 118, in blockLoad
    self.data_loc, self.org_idx + self.idx, 100)
  File "E:/Jupar/handwriting-ocr-master/WordClassDM.py", line 50, in loadImages
    printProgressBar(i - idx, upper - idx - 1)
  File "E:\Jupar\handwriting-ocr-master\ocr\viz.py", line 20, in printProgressBar
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
ZeroDivisionError: float division by zero

Process finished with exit code 1
No changes to the words_raw data.

**Comment by Breta01** [comment]
The `printProgressBar()` is just for visualisation of loading, you can remove it.
It looks like the `-1` shoudn't be there.

**Comment by juparrrr** [comment]
Thank you very much for your reply,
I encountered a problem and I tried to run Classifier-BiRNN.ipynb but the operation failed:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-19875ee213b9> in <module>()
      6                                     slider_size,
      7                                     slider_step,
----> 8                                     train=True)
      9 test_iterator = BucketDataIterator(testImages,
     10                                    testGaplines,

<ipython-input-5-56f79831ab85> in __init__(self, images, gaplines, gap_span, num_buckets, slider, slider_step, imgprocess, train)
     12 
     13         self.train = train
---> 14         length = [(image.shape[1]-slider[1])//slider_step for image in images]
     15 
     16         # Creating indices from gaplines

<ipython-input-5-56f79831ab85> in <listcomp>(.0)
     12 
     13         self.train = train
---> 14         length = [(image.shape[1]-slider[1])//slider_step for image in images]
     15 
     16         # Creating indices from gaplines

AttributeError: 'NoneType' object has no attribute 'shape'
Another problem is that I want to know where GapClassifier-BiRNN puts the cut picture.

**Comment by juparrrr** [comment]
Thanks for your help, your program is very good

**Comment by juparrrr** [comment]
I encountered such a problem when training my own dataset. How can I change it?
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-19875ee213b9> in <module>()
      6                                     slider_size,
      7                                     slider_step,
----> 8                                     train=True)
      9 test_iterator = BucketDataIterator(testImages,
     10                                    testGaplines,

<ipython-input-5-56f79831ab85> in __init__(self, images, gaplines, gap_span, num_buckets, slider, slider_step, imgprocess, train)
     35                     ind[-1] = length[i] - 1
     36 
---> 37                 targets_seq[i][ind] = POS
     38 
     39         # Create pandas dataFrame and sort it by images seq lenght (length)

IndexError: index 8 is out of bounds for axis 0 with size 8

**Comment by juparrrr** [comment]
GapClassifier-BiRNN encountered this problem when training my own dataset. How can I change it?
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-19875ee213b9> in <module>()
      6                                     slider_size,
      7                                     slider_step,
----> 8                                     train=True)
      9 test_iterator = BucketDataIterator(testImages,
     10                                    testGaplines,

<ipython-input-5-56f79831ab85> in __init__(self, images, gaplines, gap_span, num_buckets, slider, slider_step, imgprocess, train)
     35                     ind[-1] = length[i] - 1
     36 
---> 37                 targets_seq[i][ind] = POS
     38 
     39         # Create pandas dataFrame and sort it by images seq lenght (length)

IndexError: index 8 is out of bounds for axis 0 with size 8
