### ISSUE TITLE
--> 13 segRNNGraph = Graph('models/gap-clas/RNN/Bi-RNN-new', 'prediction')

### ISSUE THREAD

**Issue by beyhangl** [Breta01/handwriting-ocr#3]
---------------------------------------------------------------------------
OutOfRangeError                           Traceback (most recent call last)
<ipython-input-8-dc8d821d0ddf> in <module>()
     11 # Import costume functions, corresponding to notebooks
     12 from ocr.normalization import imageNorm, letterNorm
---> 13 from ocr import page, words, charSeg
     14 from ocr.helpers import implt, resize
     15 from ocr.tfhelpers import Graph

/home/kafein/Downloads/handwriting-ocr-master/ocr/charSeg.py in <module>()
     11 print("Loading Segmantation model:")
     12 segCNNGraph = Graph('models/gap-clas/CNN-CG')
---> 13 segRNNGraph = Graph('models/gap-clas/RNN/Bi-RNN-new', 'prediction')
     14 
     15 def classify(img, step=2, RNN=False):

/home/kafein/Downloads/handwriting-ocr-master/ocr/tfhelpers.py in __init__(self, loc, operation, input_name)
     21         with self.graph.as_default():
     22             saver = tf.train.import_meta_graph(loc + '.meta', clear_devices=True)
---> 23             saver.restore(self.sess, loc)
     24             self.op = self.graph.get_operation_by_name(operation).outputs[0]
     25 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.pyc in restore(self, sess, save_path)
   1664     if context.in_graph_mode():
   1665       sess.run(self.saver_def.restore_op_name,
-> 1666                {self.saver_def.filename_tensor_name: save_path})
   1667     else:
   1668       self._build_eager(save_path, build_save=False, build_restore=True)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    887     try:
    888       result = self._run(None, fetches, feed_dict, options_ptr,
--> 889                          run_metadata_ptr)
    890       if run_metadata:
    891         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1118     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1119       results = self._do_run(handle, final_targets, final_fetches,
-> 1120                              feed_dict_tensor, options, run_metadata)
   1121     else:
   1122       results = []

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1315     if handle is None:
   1316       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1317                            options, run_metadata)
   1318     else:
   1319       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1334         except KeyError:
   1335           pass
-> 1336       raise type(e)(node_def, op, message)
   1337 
   1338   def _extend_graph(self):

OutOfRangeError: Read less bytes than requested
	 [[Node: save/RestoreV2_67 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_67/tensor_names, save/RestoreV2_67/shape_and_slices)]]

Caused by op u'save/RestoreV2_67', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-dc8d821d0ddf>", line 13, in <module>
    from ocr import page, words, charSeg
  File "ocr/charSeg.py", line 13, in <module>
    segRNNGraph = Graph('models/gap-clas/RNN/Bi-RNN-new', 'prediction')
  File "ocr/tfhelpers.py", line 22, in __init__
    saver = tf.train.import_meta_graph(loc + '.meta', clear_devices=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1810, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 660, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): Read less bytes than requested
	 [[Node: save/RestoreV2_67 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_67/tensor_names, save/RestoreV2_67/shape_and_slices)]]

**Comment by Breta01** [comment]
Hi,
I am looking into the issues. First I am using Python 3.6 and I am afraid that you are using 2.7.
However, this doesn't look like Python problem. Could you report me your TensorFlow version?
I am using TensorFlow 1.4.0 and there may be some compatibility issues.

**Comment by beyhangl** [comment]
Hi,

My tensorflow version is 1.4.0 bu python version 2.7.
Do you think is it because of python version ?

**Comment by Breta01** [comment]
Well, I tested different versions of TensorFlow and also Python 2.7.
The problem is somewhere else because I coud restore the model on TensorFlow 1.4 with Python 2.7.
Could you check if you have the file:
`handwriting-ocr/models/gap-clas/RNN/Bi-RNN-new.data-00000-of-00001`
I am using the [Git LFS](https://git-lfs.github.com/) for storing this large file and I am not sure if you can clone it without installing this extension.

Let me know if this is the case.
BTW, you should probably still use Python 3.6 for this project, because there may be other issues.
