### ISSUE TITLE
Problem with fourCornersSort() function [help wanted]

### ISSUE THREAD

**Issue by flavienbwk** [Breta01/handwriting-ocr#31]
Hello,

I am trying to use your code that crops the image for scanned photos.

But I am getting the following error : 
```
Traceback (most recent call last):
  File "modules/border_check/processor.py", line 145, in <module>
    pageContour = findPageContours(closedEdges, resize(image, height))
  File "modules/border_check/processor.py", line 102, in findPageContours
    pageContour = fourCornersSort(pageContour[:, 0])
  File "modules/border_check/processor.py", line 55, in fourCornersSort
    diff = np.diff(pts, axis=1)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1935, in diff
    axis = normalize_axis_index(axis, nd)
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1
```

Here is what is in line 102 : 
```
pageContour = fourCornersSort(pageContour[:, 0])
```
This line is in the `findPageContours()` function.

What I get for the `pageContour` variable is : 
```
[[  0   0]
 [  0 542]
 [424 542]
 [424   0]]
```
And for `pageContour[:, 0]` : 
```
[  0   0 424 424]
```

Have you an idea of what is the problem?

Thank you and have a great day.

**Comment by Breta01** [comment]
I will fix that.
