### ISSUE TITLE
Error while training the model

### ISSUE THREAD

**Issue by ayush7506** [Breta01/handwriting-ocr#67]
While training the model on IAM Dataset using word_classifier_CTC, I got this error:
Traceback (most recent call last):
  File "word_classifier_CTC.py", line 532, in <module>
    train_step.run(fd)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/f                                                                                                                     ramework/ops.py", line 2241, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/f                                                                                                                     ramework/ops.py", line 4986, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/c                                                                                                                     lient/session.py", line 877, in run
    run_metadata_ptr)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/c                                                                                                                     lient/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/c                                                                                                                     lient/session.py", line 1272, in _do_run
    run_metadata)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/c                                                                                                                     lient/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Saw a non-null lab                                                                                                                     el (index >= num_classes - 1) following a null label, batch: 2 num_classes: 54 l                                                                                                                     abels: 37,35,46,31
         [[Node: CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_output                                                                                                                     s_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost                                                                                                                     /replica:0/task:0/device:CPU:0"](Reshape_1, _arg_targets/indices_0_3, _arg_targe                                                                                                                     ts/values_0_5, _arg_inputs_length_0_1)]]

Caused by op 'CTCLoss', defined at:
  File "word_classifier_CTC.py", line 464, in <module>
    ctc_loss = tf.nn.ctc_loss(targets, logits, inputs_length)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/o                                                                                                                     ps/ctc_ops.py", line 158, in ctc_loss
    ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/o                                                                                                                     ps/gen_ctc_ops.py", line 285, in ctc_loss
    name=name)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/f                                                                                                                     ramework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/u                                                                                                                     til/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/f                                                                                                                     ramework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/data/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/f                                                                                                                     ramework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Saw a non-null label (index >= n                                                                                                                     um_classes - 1) following a null label, batch: 2 num_classes: 54 labels: 37,35,4                                                                                                                     6,31
         [[Node: CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_output                                                                                                                     s_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost                                                                                                                     /replica:0/task:0/device:CPU:0"](Reshape_1, _arg_targets/indices_0_3, _arg_targe                                                                                                                     ts/values_0_5, _arg_inputs_length_0_1)]]
How do I resolve this?

**Comment by Breta01** [comment]
Hi,
I didn't test the training since rework, so there might be some issues. This problem is probably caused due to the wrong value in `char_size` (number of labels). IAM dataset includes some characters which I previously ignored. Try setting it to `char_size = 67`.
Please let me know if it works.

I will try to look into the problem by myself as soon as possible.
