### ISSUE TITLE
InvalidArgumentError: You must feed a value for placeholder tensor 'inputs_length_1' with dtype int32 and shape [?]

### ISSUE THREAD

**Issue by Tejas111** [Breta01/handwriting-ocr#98]
I have trained the CTC model for breta using the word-classifier-CTC .ipynb and I have trained for 2000 batches. So, the model is named as classifier1-2000. However when I run the last part of ocr.ipynb file for recognition using the CTC model. 
I ran the following code:

```
def recognise(img):
    """Recognising words using CTC Model."""
    img = word_normalization(
        img,
        64,
        border=False,
        tilt=False,
        hyst_norm=False)
    length = img.shape[1]
    # Input has shape [batch_size, height, width, 1]
    input_imgs = np.zeros(
            (1, 64, length, 1), dtype=np.uint8)
    input_imgs[0][:, :length, 0] = img

    pred = CTC_MODEL.eval_feed({
        'inputs:0': input_imgs,
        'inputs_length:0': [length],
        'keep_prob:0': 1})[0]

    word = ''
    for i in pred:
        word += idx2char(i)
    return word

implt(crop)
for line in lines:
    print(" ".join([recognise(crop[y1:y2, x1:x2]) for (x1, y1, x2, y2) in line]))
```

I got the following error:
```
InvalidArgumentError                      Traceback (most recent call last)
C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: You must feed a value for placeholder tensor 'inputs_length_1' with dtype int32 and shape [?]
	 [[{{node inputs_length_1}} = Placeholder[dtype=DT_INT32, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-19-00a9b54c67c5> in <module>()
     25 implt(crop)
     26 for line in lines:
---> 27     print(" ".join([recognise(crop[y1:y2, x1:x2]) for (x1, y1, x2, y2) in line]))

<ipython-input-19-00a9b54c67c5> in <listcomp>(.0)
     25 implt(crop)
     26 for line in lines:
---> 27     print(" ".join([recognise(crop[y1:y2, x1:x2]) for (x1, y1, x2, y2) in line]))

<ipython-input-19-00a9b54c67c5> in recognise(img)
     16         'inputs:0': input_imgs,
     17         'inputs_length:0': [length],
---> 18         'keep_prob:0': 1})[0]
     19 
     20     word = ''

C:\Users\HP\Desktop\handwriting-ocr\src\ocr\tfhelpers.py in eval_feed(self, feed)
     30     def eval_feed(self, feed):
     31         """Run the specified operation with given feed."""
---> 32         return self.sess.run(self.op, feed_dict=feed)
     33 
     34     def run_op(self, op, feed, output=True):

C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: You must feed a value for placeholder tensor 'inputs_length_1' with dtype int32 and shape [?]
	 [[node inputs_length_1 (defined at C:\Users\HP\Desktop\handwriting-ocr\src\ocr\tfhelpers.py:22)  = Placeholder[dtype=DT_INT32, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'inputs_length_1', defined at:
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 301, in run_forever
    self._run_once()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1198, in _run_once
    handle._run()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2705, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2809, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2869, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-042b2a659816>", line 2, in <module>
    CTC_MODEL = Model(MODEL_LOC_CTC, 'word_prediction')
  File "C:\Users\HP\Desktop\handwriting-ocr\src\ocr\tfhelpers.py", line 22, in __init__
    saver = tf.train.import_meta_graph(loc + '.meta', clear_devices=True)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 3440, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 3440, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 3299, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'inputs_length_1' with dtype int32 and shape [?]
	 [[node inputs_length_1 (defined at C:\Users\HP\Desktop\handwriting-ocr\src\ocr\tfhelpers.py:22)  = Placeholder[dtype=DT_INT32, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

**Comment by Breta01** [comment]
This looks like you might run the training script twice which resulted in double initialization of variables.

I am planning on updating the scripts, so that it supports retraining and resetting the training from last checkpoint. Hopefully will have some time to do it soon.

**Comment by Tejas111** [comment]
Thanks for replying, I will try to clear the model and start from the beginning
